---
title: "Project"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load data
```{r }
library(readxl)
df = read_excel("World Happiness Report 2021.xls")
print(head(df))
```
```{r}
factors <- factor(df[['Regional indicator']])
region_color = as.numeric(factors)
```


```{r }
cat("rows: ", nrow(df), ", cols:", ncol(df))
```
```{r }
colnames(df)
```
```{r}
df_x = df[c("Social support", "Generosity", "Healthy life expectancy", 
            "Logged GDP per capita", "Freedom to make life choices", 
            "Perceptions of corruption" 
            )]
row.names(df_x) <- df[["Country name"]]
```


# Do PCA
```{r}

library(FactoMineR)
pca <- PCA(df_x, ncp = 6, graph = FALSE, scale.unit = TRUE)

library(factoextra)
## eigenvalue (variances of each principal components)
eig.val <- get_eigenvalue(pca)
eig.val

# eigen vectors (the coefficients of each principal components)
pca$svd$V  
```

```{r}

summary(pca)

```

```{r}
pca$ind$coord
```

# Visualize
## Visualize eigenvalues/variances
```{r }

fviz_screeplot(pca, addlabels = TRUE, ylim = c(0, 55), barfill = "skyblue", barcolor = "skyblue")

```
## 分數圖 (score plot)
如果個體的變量特徵相近，他們會在圖中聚在較爲靠近的地方
```{r}
#fviz_pca_ind(pca, pointsize = "cos2", pointshape = 21, fill = "#E7B800", repel = TRUE, labelsize = 2) 
fviz_pca_ind(pca, col.ind = "cos2", 
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE # Avoid text overlapping (slow if many points)
             )
```
```{r}
fviz_pca_ind(pca, col.ind = "contrib", 
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE # Avoid text overlapping (slow if many points)
             )
```

```{r}
fviz_pca_ind(pca, label="none", habillage=factors,
             addEllipses=TRUE, ellipse.level=0.95, palette = "Dark2")
```


## 輔助性變量的變量相關圓盤圖
```{r }
#fviz_pca_var(pca, repel = TRUE) 

# Control variable colors using their contributions
fviz_pca_var(pca, axes = c(1, 2), col.var = "contrib",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE # Avoid text overlapping
             )
```

## Variable contributions to the principal axes
```{r}
# Contributions of variables to PC1
fviz_contrib(pca, choice = "var", axes = 1, top = 10)

# Contributions of variables to PC2
fviz_contrib(pca, choice = "var", axes = 2, top = 10)
```

```{r}
fviz_pca_ind(pca,
             label = "none", # hide individual labels
             habillage = factors, # color by groups
             #palette = c("#00AFBB", "#E7B800", "#FC4E07"),
             addEllipses = TRUE # Concentration ellipses
             )
```



```{python}




```

